sudo: required
dist: trusty

language: node_js
node_js:
  - 12.2.0

services:
  - docker

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_install:
  - ./before_install.sh
  - ./bin/aws-encryption-cli --decrypt -S --input .env.enc --output .env

install:
  - echo Installing

before_script:
  - echo Before script

script:
  - echo Script

after_success:
  - echo Success!

env:
  global:
    - NODE_ENV=test
    - AWS_PROFILE=default
    - secure: gZ6OhfAaoWB7yeAY9mNbUtFh1vFOkqSbiClq1EqRIc71/dNKL9NfayHz+xLlIzINLRhV3/Y9ReJ+JLhy+uLcXkqD1HljiwuLLV8y7ZUmK+tkn7iO8njgEoTZjSQdvuICCOcFKXNQinzQo39ZAVRBi31HRIFWRDIGU2GQQR1HCgYbBTrm2+UiD+UhAjEpzqaIElGgvhAdPXGyThb0CboFepU03HrbSf1iV4I7/R0owC5tfsg6qW5kE9S7SvaJjBYJmP8Et4uWglfKSDw/x1QNwoiHw9GyRtKDHMZ8gvrq0OfEvCf2p/MspViig3SAaj9eSJM3WPSBfJlhV7YDh4FKFH6OTrug15nEvV2S03fz4xUGP2m35sNcjASkZl5j+fzAOCiOIpD3Fg1kEt71Bw89x8wVH6kn0zkyyfk3N3A4Qafpi+F1jM7TbH0kdONRn6kuutqgvNQjyaFEbUoJ4D/hhqpgJZ3OuaOO+hbHRe+7qjGyhd4uqB+rgNiSTdOHX6MuNXgrGWvb6O3niew1gAEEFkTmJFyNL5hlJFBy+pd2W+/h4NhxIH8CC30NurL2MFmlML6exc6BPYRRl1ZLMxv7G5f8cPggTjQ6Ojs/wB0eqDvhQHi+coOEL2iHiHsB+CMglvmOg3x9NLq0gKwHFnEX/3H6YRTuVfRJ4YQs4PKWGNs=

deploy:
  - provider: heroku
    skip_cleanup: true
    api_key:
      secure: VoS00mKg9gEGjVkPcYb7fmIxSyI9wYlXl23A2rzyc/HeooU33cPR8pd2HuJK3JTrgyHXPnyT9Sj7Kz/4i49vdW1IP3KlHjbTxwAAp5Cv0QjY6pfg6dAxw6LqzPYTbgkXFKoFNLxLbNkwquRwnPC3xY/11BTaUGZBUQPNJXubRZBH7VVB4A9hxR1q8LAk5zjnSof9YQ2gBrWC5iRZqKnKYztlA0pZa1qtuAMSNgnofiSbA1pllmPoQF1dJdoGGvNqsEopKQFzXXUNQk2AdtEyvRPwTzAYWs5e4Bm0skbaBvO0TmrqtsHFm1tp5GsNJ49iYeb35Tva8JOcwq7Kn5I8xO2pkc1qBDAyD+aPsiUk1pJyM6AR+8Tnvjdk74mszEmEmJLoQiIwvGIyNPd2aQpDKEyd2utDzKCI7T4R06/e41t+e+dAMZsgNRM/TWlh8y3KvQTzg525EgliWP95vFIloezR+pAL4r6CFdmVged4TeruvsnLBHF6UUBD+ld2tvgvlcrjAzmOQt/Cl5I4h+R2DqyfkDSxl0pxZwm3svBywTpFUnj2mnHcjQJBH0d7VZbI/ViMi9vF+qeo3tKrZFQcF0q7a2vdEsmyH3eiB8wQ5qq3RAyou5eJPh3peU/HR0AT4IgjJHHnkAaRUULaNezlRgLkAxkJRgL47KghGRKxMJo=
    app:
      master: aws-secrets-meeting
    on:
      repo: jlsan92/aws-secrets-meeting

notifications:
  email: false
